# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: bobs
description: BOBS temporary spool storage service
type: application
version: 0.1.2
appVersion: 0.1.0
