# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
#
# SPDX-License-Identifier: Apache-2.0

# {{- include "bobs.validateConfigBounds" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "bobs.nameWithSuffix" (dict "base" (include "bobs.fullname" .) "suffix" "-config") }}'
  labels:
    # prettier-ignore
    app.kubernetes.io/name: {{ include "bobs.name" . | quote }}
    # prettier-ignore
    app.kubernetes.io/instance: {{ .Release.Name | toString | quote }}
data:
  config.yaml: |
    {{- include "bobs.configYaml" . | nindent 4 }}
