apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "bobs.fullname" . }}'
  labels:
    app.kubernetes.io/name: '{{ include "bobs.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "bobs.name" . }}'
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ include "bobs.name" . }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      subdomain: '{{ .Values.headlessService.name }}'
      containers:
        - name: bobs
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: BOBS_LISTEN_ADDR
              value: '{{ .Values.env.BOBS_LISTEN_ADDR }}'
            - name: BOBS_DATA_DIR
              value: '{{ .Values.env.BOBS_DATA_DIR }}'
            - name: BOBS_PAGE_SIZE
              value: '{{ .Values.env.BOBS_PAGE_SIZE }}'
            - name: BOBS_MAX_CACHE_BYTES
              value: '{{ .Values.env.BOBS_MAX_CACHE_BYTES }}'
            - name: BOBS_WRITER_INACTIVITY_TIMEOUT_SECS
              value: '{{ .Values.env.BOBS_WRITER_INACTIVITY_TIMEOUT_SECS }}'
            - name: BOBS_READER_DONE_TTL_SECS
              value: '{{ .Values.env.BOBS_READER_DONE_TTL_SECS }}'
            - name: BOBS_UNREAD_TTL_SECS
              value: '{{ .Values.env.BOBS_UNREAD_TTL_SECS }}'
            - name: BOBS_CLEANUP_SWEEP_INTERVAL_SECS
              value: '{{ .Values.env.BOBS_CLEANUP_SWEEP_INTERVAL_SECS }}'
          resources: {}
          volumeMounts:
            - name: data
              mountPath: '{{ .Values.env.BOBS_DATA_DIR }}'
      volumes:
        - name: data
          emptyDir: {}
