# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
#
# SPDX-License-Identifier: Apache-2.0

# {{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  # prettier-ignore
  name: {{ include "bobs.headlessServiceName" . | quote }}
  labels:
    # prettier-ignore
    app.kubernetes.io/name: {{ include "bobs.name" . | quote }}
    # prettier-ignore
    app.kubernetes.io/instance: {{ .Release.Name | toString | quote }}
spec:
  clusterIP: None
  ports:
    # prettier-ignore
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    # prettier-ignore
    app.kubernetes.io/name: {{ include "bobs.name" . | quote }}
    # prettier-ignore
    app.kubernetes.io/instance: {{ .Release.Name | toString | quote }}
# {{- end }}
