# SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
#
# SPDX-License-Identifier: Apache-2.0

# {{- if and .Values.config.metrics.enabled .Values.config.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # prettier-ignore
  name: {{ include "bobs.fullname" . | quote }}
  labels:
    # {{- include "bobs.serviceMonitorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      # prettier-ignore
      app.kubernetes.io/name: {{ include "bobs.name" . | quote }}
      # prettier-ignore
      app.kubernetes.io/instance: {{ .Release.Name | toString | quote }}
  endpoints:
    - port: metrics
      path: /metrics
      # prettier-ignore
      interval: {{ .Values.config.metrics.serviceMonitor.interval | toString | quote }}
# {{- end }}
