export VIRTUAL_ENV := ".venv"
export PATH := VIRTUAL_ENV + "/bin:" + env_var('PATH')
# this makes all the commands here use the local venv
# set dotenv-path := ".env" # TODO fix and replace the explicit ones

setup_venv:
    #!/bin/bash
    if [ ! -d "$VIRTUAL_ENV" ] ; then
        if ! command -v uv 2>&1 > /dev/null ; then
            python -m venv "$VIRTUAL_ENV"
        else
            uv venv -p python3.12 "$VIRTUAL_ENV"
        fi
        # echo 'VIRTUAL_ENV=".venv"' > .env
        # echo 'PATH="$VIRTUAL_ENV/bin:$PATH"' >> .env
    fi

setup: setup_venv
    #!/bin/bash
    if ! command -v uv 2>&1 > /dev/null ; then
        pip install uv
    fi
    uv pip install -e '.[test]'

run:
    python -m pest

test:
    pytest -s tests

mypy:
    # TODO where to put?
    # dmypy start -- --ignore-missing-imports
    # TODO somehow doesnt work because of packages/names -- fix
    # dmypy check src tests
    mypy --ignore-missing-imports -p pest
    mypy --ignore-missing-imports tests
